Section "InputClass"
    Identifier "keyboard-all"
    Driver "evdev"
    Option "XkbLayout" "us,ru"
    Option "XkbVariant" ",winkeys"
    Option "XkbOptions" "grp:win_space_toggle,grp_led:scroll"
    MatchIsKeyboard "on"
EndSection
